# 8 jobs
# wandb:
#   group: color-1b
seed: 1

device_train_microbatch_size: 32
model:
  d_model: 1024
  max_sequence_length: 2048
  mlp_hidden_size: 8192
  n_heads: 8
  n_layers: 24
save_folder: /n/holyscratch01/sham_lab/dclm/color_filter_data/first_run
time_limit: 2100000 # 600 hrs
max_duration: 192000 # 24B tokens (8x 24k steps)
scheduler: 
  t_warmup: 2000

optimizer:
  name: adamw
  learning_rate: 0.003
  weight_decay: 0.033
  eps: 1e-15
  betas:
  - 0.9
  - 0.95
  metrics_log_interval: 100