run_name: score-8b-reduced
seed: 1
dry_run: false

restore_dataloader: false
reset_optimizer_state: true
reset_trainer_state: true
load_path: prior
load_checkpoint_type: unsharded
eval_on_load: false
max_duration: 1ep
sweep:
  - data: 
      paths: conditional_data
    scheduler:
      t_warmup: 20

global_train_batch_size: 256
device_train_microbatch_size: 8
model:
  d_model: 768
  max_sequence_length: 2048
  mlp_hidden_size: 3072
  n_heads: 8
  n_layers: 12