# 8 jobs
wandb:
  project: DCLM
  entity: hamshoe
  name: fineweb-3b-baseline

seed: 1

device_train_microbatch_size: 8
  
time_limit: 2100000 # 600 hrs
max_duration: 1ep # 3B tokens

data:
  paths: finewebedu-3B