run_name: pretrain-8b
seed: 0
dry_run: false

max_duration: 24000 # ~3B tokens for batches of 256 x 512
global_train_batch_size: 256 
device_train_microbatch_size: 8 # adjusted

# TODO: add your own wandb information
# wandb:
#   name: ${run_name}
#   log_interval: ${console_log_interval}
#   entity: YOUR_ENTITY
#   project: color-filter
#   group: debug

model:
  d_model: 768 # adjusted down from 1024
  mlp_hidden_size: 3192 # adjusted to 4 * d_model
  n_heads: 8 # adjusted, 16 before
  n_layers: 24 # adjusted, 12 before
  max_sequence_length: 2048 # adjusted, 512 before
  rope: true
  attention_layer_norm: true
  attention_layer_norm_with_affine: true 
  multi_query_attention: false
  include_bias: false
  block_type: sequential
  layer_norm_type: default
  layer_norm_with_affine: true 
  bias_for_layer_norm: false
  activation_type: gelu 
  attention_dropout: 0.0
  residual_dropout: 0.0
  embedding_dropout: 0.0
  vocab_size: 50280
  embedding_size: 50304
  eos_token_id: 0
  pad_token_id: 1
  init_device: meta
  init_fn: mitchell
  weight_tying: false

compile:
  mode: default

precision: amp_bf16
max_grad_norm: 1.0

fsdp:
  precision: mixed
  sharding_strategy: FULL_SHARD

scheduler:
  name: cosine_with_warmup
  t_warmup: 2000 # adjusted, 1000 before
  alpha_f: 0.1

optimizer:
  name: adamw
  learning_rate: 0.003
  weight_decay: 0.033
  eps: 1e-15
  betas:
  - 0.9
  - 0.95
  metrics_log_interval: 100

activation_checkpointing: false
softmax_auxiliary_loss: true

data:
  paths: prior_data
  pad_direction: right
  num_workers: 16 
  drop_last: true
  pin_memory: true
  prefetch_factor: 16
  persistent_workers: true
  timeout: 0
  extra_data_paths: null

tokenizer:
  identifier: allenai/eleuther-ai-gpt-neox-20b-pii-special 
  truncate_direction: right

# save_folder: ${oc.env:CHECKPOINTS_PATH}/${run_name}
save_folder: /n/netscratch/sham_lab/Everyone/dclm/color_filter/models/prior_8b/${run_name}
save_overwrite: true
# Sharded checkpoints (best for restarts)
save_interval: 5000
save_num_checkpoints_to_keep: 1
# Unsharded checkpoints (for final storage)
save_interval_unsharded: 100000
save_num_unsharded_checkpoints_to_keep: 1 # only save last checkpoint

load_path: null