epoch: 1.25T
dataset: bigdata
num_params: 1B
max_seq_len: 2048
seed: 1
precision: fp32

# Tokenizer
tokenizer:
  # name: [Add name from memory]
  pretrained_model_name_or_path:
  kwargs:
    model_max_length: 2048

model:
  name: open_lm
  # pretrained_model_name_or_path: [add name from memory]
  init_device: cpu
  pretrained: true

load_path: # Add your (optional) Composer checkpoint path here!

device_eval_batch_size: 2

# FSDP config for model sharding
fsdp_config:
  sharding_strategy: FULL_SHARD
  mixed_precision: FULL


icl_tasks:
-
  label: mmlu_aux
  dataset_uri: cais/mmlu
  dataset_second: all
  choice_col: choices
  num_fewshot: [0]
  icl_task_type: multiple_choice
  question_prelimiter: "\nQuestion: "
  continuation_delimiter: "\nAnswer: "
  has_categories: true
-
  label: commonsense_qa
  dataset_uri: tau/commonsense_qa
  choice_col: choices
  choice_index: "text"
  answer_col: answerKey
  num_fewshot: [10]
  icl_task_type: multiple_choice
  question_prelimiter: "\nQuestion: "
  continuation_delimiter: "\nAnswer: "
-
  label: hellaswag
  dataset_uri: Rowan/hellaswag
  question_col: ctx
  choice_col: endings
  answer_col: label
  num_fewshot: [0]
  icl_task_type: multiple_choice

-
  label: jeopardy
  dataset_uri: "openaccess-ai-collective/jeopardy"
  num_fewshot: [10]
  icl_task_type: language_modeling
  question_prelimiter: "\nQuestion: "
  continuation_delimiter: "\nAnswer: "
  has_categories: true
-
  label: arc_easy
  dataset_uri: "allenai/ai2_arc"
  dataset_second: "ARC-Easy"
  choice_col: choices
  answer_col: answerKey
  num_fewshot: [10]
  icl_task_type: multiple_choice
  question_prelimiter: "\nQuestion: "
  continuation_delimiter: "\nAnswer: "
-
  label: arc_challenge
  dataset_uri: allenai/ai2_arc
  dataset_second: ARC-Challenge
  choice_col: choices
  answer_col: answerKey
  num_fewshot: [10]
  icl_task_type: multiple_choice
  question_prelimiter: "\nQuestion: "
  continuation_delimiter: "\nAnswer: " 

-
  label: openbook_qa_main
  dataset_uri: allenai/openbookqa
  dataset_second: main
  question_col: question_stem
  choice_col: choices
  answer_col: answerKey
  num_fewshot: [0]
  icl_task_type: multiple_choice
  question_prelimiter: "\nQuestion: "
  continuation_delimiter: "\nAnswer: "

# -
#   label: lambada_openai
#   dataset_uri: cimec/lambada
#   context_col: text
#   num_fewshot: [0]
#   icl_task_type: language_modeling

-
  label: gsm8k
  dataset_uri: "openai/gsm8k"
  dataset_second: "main"
  question_prelimiter: "\nQuestion: "
  continuation_delimiter: "\nAnswer: "
-
  label: squad
  dataset_uri: rajpurkar/squad_v2
  num_fewshot: [10]
  context_col: context
  question_col: question
  answer_col: answers
  question_prelimiter: "\nQuestion: "
  continuation_delimiter: "\nAnswer: "
  icl_task_type: language_modeling
-
  label: coqa
  dataset_uri: stanfordnlp/coqa
  context_col: story
  question_col: questions
  answer_col: answers
  num_fewshot: [0]
  icl_task_type: language_modeling
-
  label: boolq
  dataset_uri: google/boolq
  question_col: question
  answer_col: answer
  num_fewshot: [10]
  icl_task_type: multiple_choice
  question_prelimiter: "\nQuestion: "
  continuation_delimiter: "\nAnswer: "
