tar_paths: "/n/netscratch/sham_lab/Everyone/dclm/color_filter/data/tokshuf/mmlu-aux-trainset/*.tar"
memmap_path: "/n/netscratch/sham_lab/Everyone/dclm/color_filter/data/memmap/mmlu-aux-trainset"
processes: null # Set to number of processes wanted to process tars. Defaults to number of CPU cores.